[package]
name = "in_memory_dropper"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.29"
log = "0.4"
env_logger = "0.10"
hex = "0.4"
winapi = "0.3.9"

[profile.release]
opt-level = "z"
lto = true
strip = true
