[package]
name = "ransomware"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.7"
sha2 = "0.10"
rand = "0.8"
cipher = "0.3"
walkdir = "2.5"
generic-array = "0.14"

[profile.release]
strip = true 
lto = true
